export const lithuanianNumbers: string[] = [
  "vienas",
  "du",
  "trys",
  "keturi",
  "penki",
  "šeši",
  "septyni",
  "aštuoni",
  "devyni",
  "dešimt",
  "vienuolika",
  "dvylika",
  "trylika",
  "keturiolika",
  "penkiolika",
  "šešiolika",
  "septyniolika",
  "aštuoniolika",
  "devyniolika",
  "dvidešimt",
  "dvidešimt vienas",
  "dvidešimt du",
  "dvidešimt trys",
  "dvidešimt keturi",
  "dvidešimt penki",
  "dvidešimt šeši",
  "dvidešimt septyni",
  "dvidešimt aštuoni",
  "dvidešimt devyni",
  "trisdešimt",
  "trisdešimt vienas",
  "trisdešimt du",
  "trisdešimt trys",
  "trisdešimt keturi",
  "trisdešimt penki",
  "trisdešimt šeši",
  "trisdešimt septyni",
  "trisdešimt aštuoni",
  "trisdešimt devyni",
  "keturiasdešimt",
  "keturiasdešimt vienas",
  "keturiasdešimt du",
  "keturiasdešimt trys",
  "keturiasdešimt keturi",
  "keturiasdešimt penki",
  "keturiasdešimt šeši",
  "keturiasdešimt septyni",
  "keturiasdešimt aštuoni",
  "keturiasdešimt devyni",
  "penkiasdešimt",
  "penkiasdešimt vienas",
  "penkiasdešimt du",
  "penkiasdešimt trys",
  "penkiasdešimt keturi",
  "penkiasdešimt penki",
  "penkiasdešimt šeši",
  "penkiasdešimt septyni",
  "penkiasdešimt aštuoni",
  "penkiasdešimt devyni",
  "šešiasdešimt",
  "šešiasdešimt vienas",
  "šešiasdešimt du",
  "šešiasdešimt trys",
  "šešiasdešimt keturi",
  "šešiasdešimt penki",
  "šešiasdešimt šeši",
  "šešiasdešimt septyni",
  "šešiasdešimt aštuoni",
  "šešiasdešimt devyni",
  "septyniasdešimt",
  "septyniasdešimt vienas",
  "septyniasdešimt du",
  "septyniasdešimt trys",
  "septyniasdešimt keturi",
  "septyniasdešimt penki",
  "septyniasdešimt šeši",
  "septyniasdešimt septyni",
  "septyniasdešimt aštuoni",
  "septyniasdešimt devyni",
  "aštuoniasdešimt",
  "aštuoniasdešimt vienas",
  "aštuoniasdešimt du",
  "aštuoniasdešimt trys",
  "aštuoniasdešimt keturi",
  "aštuoniasdešimt penki",
  "aštuoniasdešimt šeši",
  "aštuoniasdešimt septyni",
  "aštuoniasdešimt aštuoni",
  "aštuoniasdešimt devyni",
  "devyniasdešimt",
  "devyniasdešimt vienas",
  "devyniasdešimt du",
  "devyniasdešimt trys",
  "devyniasdešimt keturi",
  "devyniasdešimt penki",
  "devyniasdešimt šeši",
  "devyniasdešimt septyni",
  "devyniasdešimt aštuoni",
  "devyniasdešimt devyni",
  "šimtas",
];
